<div class="logoCenter"> 
  <p> BIENVENUE DANS LE BIBLIOTHEQUE DE N’GAOUNDÉRÉ </p>
  <p> << UNE BIBLIOTHEQUE EST UN TRESOR DE SAVOIR, DE CULTURE     ET D'HISTOIRE QUI APPARTIENT A TOUS >> </p>
  <p> LES LIVRES SONT DES ABEILLES QUI TRANSPORTENT RAPIDEMENT DE FLEURE EN FLEURE L'INTELLIGENCE DU MONDE >> </p>

  <img src="/assets/img/1.jpg" >

</div>